"base_path": ".."
"preserve_hierarchy": true
"files": [
  {
    "source": "/SharkFarm/Localization/Strings.resx",
    "translation": "/SharkFarm/Localization/Strings.%locale%.resx",
    "translation_replace": {
      ".bs-BA.resx": ".bs-Latn.resx",
      ".lol-US.resx": ".qps-Ploc.resx",
      ".sr-CS.resx": ".sr-Latn.resx",
      ".zh-CN.resx": ".zh-Hans.resx",
      ".zh-HK.resx": ".zh-Hant-HK.resx",
      ".zh-TW.resx": ".zh-Hant.resx"
    }
  },
  {
    "source": "/SharkFarm.OfficialPlugins.ItemsMatcher/Localization/Strings.resx",
    "translation": "/SharkFarm.OfficialPlugins.ItemsMatcher/Localization/Strings.%locale%.resx",
    "translation_replace": {
      ".bs-BA.resx": ".bs-Latn.resx",
      ".lol-US.resx": ".qps-Ploc.resx",
      ".sr-CS.resx": ".sr-Latn.resx",
      ".zh-CN.resx": ".zh-Hans.resx",
      ".zh-HK.resx": ".zh-Hant-HK.resx",
      ".zh-TW.resx": ".zh-Hant.resx"
    }
  },
  {
    "source": "/SharkFarm.OfficialPlugins.MobileAuthenticator/Localization/Strings.resx",
    "translation": "/SharkFarm.OfficialPlugins.MobileAuthenticator/Localization/Strings.%locale%.resx",
    "translation_replace": {
      ".bs-BA.resx": ".bs-Latn.resx",
      ".lol-US.resx": ".qps-Ploc.resx",
      ".sr-CS.resx": ".sr-Latn.resx",
      ".zh-CN.resx": ".zh-Hans.resx",
      ".zh-HK.resx": ".zh-Hant-HK.resx",
      ".zh-TW.resx": ".zh-Hant.resx"
    }
  },
  {
    "source": "/SharkFarm.OfficialPlugins.SteamTokenDumper/Localization/Strings.resx",
    "translation": "/SharkFarm.OfficialPlugins.SteamTokenDumper/Localization/Strings.%locale%.resx",
    "translation_replace": {
      ".bs-BA.resx": ".bs-Latn.resx",
      ".lol-US.resx": ".qps-Ploc.resx",
      ".sr-CS.resx": ".sr-Latn.resx",
      ".zh-CN.resx": ".zh-Hans.resx",
      ".zh-HK.resx": ".zh-Hant-HK.resx",
      ".zh-TW.resx": ".zh-Hant.resx"
    }
  },
  {
    "source": "/wiki/*.md",
    "translation": "/wiki/locale/%locale%/%file_name%-%locale%.%file_extension%",
    "ignore": [ "/**/_*.md" ]
  },
  {
    "source": "/wiki/_Sidebar.md",
    "translation": "/wiki/locale/%locale%/_Sidebar.md"
  }
]
