github: SharkFarmDev
custom: ["https://paypal.me/SharkFarmDev", "https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=HD2P2P3WGS5Y4", "https://pay.revolut.com/SharkFarmDev", "https://steamcommunity.com/tradeoffer/new/?partner=46697991&token=0ix2Ruv_"]
